version: "3.7"

services:
  # Front service
  desafio-front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
          - '.:/app'
          - '/app/node_modules/'
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    tty: true